trigger: none

pool: Default

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'serviceconnectionAug'
    backendAzureRmStorageAccountName: 'sanjaystgg'
    backendAzureRmContainerName: 'sanjaycontainer'
    backendAzureRmKey: 'sanjay.tfstate'